(cl:in-package ff_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          NAME-VAL
          NAME
          CONTROL_ENABLED-VAL
          CONTROL_ENABLED
          TOLERANCE_POS_ENDPOINT-VAL
          TOLERANCE_POS_ENDPOINT
          TOLERANCE_POS-VAL
          TOLERANCE_POS
          TOLERANCE_VEL-VAL
          TOLERANCE_VEL
          TOLERANCE_ATT-VAL
          TOLERANCE_ATT
          TOLERANCE_OMEGA-VAL
          TOLERANCE_OMEGA
          TOLERANCE_TIME-VAL
          TOLERANCE_TIME
          ATT_KP-VAL
          ATT_KP
          ATT_KI-VAL
          ATT_KI
          OMEGA_KD-VAL
          OMEGA_KD
          POS_KP-VAL
          POS_KP
          POS_KI-VAL
          POS_KI
          VEL_KD-VAL
          VEL_KD
          HARD_LIMIT_VEL-VAL
          HARD_LIMIT_VEL
          HARD_LIMIT_ACCEL-VAL
          HARD_LIMIT_ACCEL
          HARD_LIMIT_OMEGA-VAL
          HARD_LIMIT_OMEGA
          HARD_LIMIT_ALPHA-VAL
          HARD_LIMIT_ALPHA
          SPEED-VAL
          SPEED
))