(cl:in-package ff_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CHILD_FRAME_ID-VAL
          CHILD_FRAME_ID
          POSE-VAL
          POSE
          VELOCITY-VAL
          VELOCITY
          OMEGA-VAL
          OMEGA
          GYRO_BIAS-VAL
          GYRO_BIAS
          ACCEL-VAL
          ACCEL
          ACCEL_BIAS-VAL
          ACCEL_BIAS
          COV_DIAG-VAL
          COV_DIAG
          CONFIDENCE-VAL
          CONFIDENCE
          AUG_STATE_ENUM-VAL
          AUG_STATE_ENUM
          STATUS-VAL
          STATUS
          OF_COUNT-VAL
          OF_COUNT
          ML_COUNT-VAL
          ML_COUNT
          HR_GLOBAL_POSE-VAL
          HR_GLOBAL_POSE
          ML_MAHAL_DISTS-VAL
          ML_MAHAL_DISTS
          ESTIMATING_BIAS-VAL
          ESTIMATING_BIAS
))