// Auto-generated. Do not edit!

// (in-package ff_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class PerchResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.response = null;
      this.fsm_result = null;
    }
    else {
      if (initObj.hasOwnProperty('response')) {
        this.response = initObj.response
      }
      else {
        this.response = 0;
      }
      if (initObj.hasOwnProperty('fsm_result')) {
        this.fsm_result = initObj.fsm_result
      }
      else {
        this.fsm_result = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PerchResult
    // Serialize message field [response]
    bufferOffset = _serializer.int32(obj.response, buffer, bufferOffset);
    // Serialize message field [fsm_result]
    bufferOffset = _serializer.string(obj.fsm_result, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PerchResult
    let len;
    let data = new PerchResult(null);
    // Deserialize message field [response]
    data.response = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [fsm_result]
    data.fsm_result = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.fsm_result.length;
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'ff_msgs/PerchResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2036823b5e70e7e2401e3c61a8196cf3';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    # Perch result
    int32 response
    int32 CANCELLED                          = 5
    int32 ALREADY_PERCHED                    = 4
    int32 ALREADY_UNPERCHED                  = 3
    int32 UNPERCHED                          = 2
    int32 PERCHED                            = 1
    int32 PREEMPTED                          = 0
    int32 INVALID_COMMAND                    = -1
    int32 NOT_IN_UNPERCHED_STATE             = -2
    int32 NOT_IN_PERCHED_STATE               = -3
    int32 SWITCH_FAILED                      = -4
    int32 MOTION_FAILED                      = -5
    int32 ARM_FAILED                         = -6
    
    # Human readable FSM result for debugging
    string fsm_result
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PerchResult(null);
    if (msg.response !== undefined) {
      resolved.response = msg.response;
    }
    else {
      resolved.response = 0
    }

    if (msg.fsm_result !== undefined) {
      resolved.fsm_result = msg.fsm_result;
    }
    else {
      resolved.fsm_result = ''
    }

    return resolved;
    }
};

// Constants for message
PerchResult.Constants = {
  CANCELLED: 5,
  ALREADY_PERCHED: 4,
  ALREADY_UNPERCHED: 3,
  UNPERCHED: 2,
  PERCHED: 1,
  PREEMPTED: 0,
  INVALID_COMMAND: -1,
  NOT_IN_UNPERCHED_STATE: -2,
  NOT_IN_PERCHED_STATE: -3,
  SWITCH_FAILED: -4,
  MOTION_FAILED: -5,
  ARM_FAILED: -6,
}

module.exports = PerchResult;
