// Generated by gencpp from file ff_msgs/ArmGripperState.msg
// DO NOT EDIT!


#ifndef FF_MSGS_MESSAGE_ARMGRIPPERSTATE_H
#define FF_MSGS_MESSAGE_ARMGRIPPERSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ff_msgs
{
template <class ContainerAllocator>
struct ArmGripperState_
{
  typedef ArmGripperState_<ContainerAllocator> Type;

  ArmGripperState_()
    : state(0)  {
    }
  ArmGripperState_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;



  enum {
    UNKNOWN = 0u,
    UNCALIBRATED = 1u,
    CALIBRATING = 2u,
    CLOSED = 3u,
    OPEN = 4u,
  };


  typedef boost::shared_ptr< ::ff_msgs::ArmGripperState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ff_msgs::ArmGripperState_<ContainerAllocator> const> ConstPtr;

}; // struct ArmGripperState_

typedef ::ff_msgs::ArmGripperState_<std::allocator<void> > ArmGripperState;

typedef boost::shared_ptr< ::ff_msgs::ArmGripperState > ArmGripperStatePtr;
typedef boost::shared_ptr< ::ff_msgs::ArmGripperState const> ArmGripperStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ff_msgs::ArmGripperState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ff_msgs::ArmGripperState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ff_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/std_msgs/cmake/../msg', '/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ff_msgs': ['/home/isuru/Forked_astrobee/astrobee/src/communications/ff_msgs/msg', '/home/isuru/Forked_astrobee/astrobee/debian/devel/.private/ff_msgs/share/ff_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ff_msgs::ArmGripperState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ff_msgs::ArmGripperState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ff_msgs::ArmGripperState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ff_msgs::ArmGripperState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ff_msgs::ArmGripperState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ff_msgs::ArmGripperState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ff_msgs::ArmGripperState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3857276ebd0698497c3781f3fb94fb88";
  }

  static const char* value(const ::ff_msgs::ArmGripperState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3857276ebd069849ULL;
  static const uint64_t static_value2 = 0x7c3781f3fb94fb88ULL;
};

template<class ContainerAllocator>
struct DataType< ::ff_msgs::ArmGripperState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff_msgs/ArmGripperState";
  }

  static const char* value(const ::ff_msgs::ArmGripperState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ff_msgs::ArmGripperState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright (c) 2017, United States Government, as represented by the\n\
# Administrator of the National Aeronautics and Space Administration.\n\
# \n\
# All rights reserved.\n\
# \n\
# The Astrobee platform is licensed under the Apache License, Version 2.0\n\
# (the \"License\"); you may not use this file except in compliance with the\n\
# License. You may obtain a copy of the License at\n\
# \n\
#     http://www.apache.org/licenses/LICENSE-2.0\n\
# \n\
# Unless required by applicable law or agreed to in writing, software\n\
# distributed under the License is distributed on an \"AS IS\" BASIS, WITHOUT\n\
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the\n\
# License for the specific language governing permissions and limitations\n\
# under the License.\n\
#\n\
# Arm Gripper State enum\n\
#\n\
# *MUST* be kept in sync with rapid::ext::astrobee::ArmState\n\
\n\
uint8 UNKNOWN      = 0\n\
uint8 UNCALIBRATED = 1\n\
uint8 CALIBRATING  = 2\n\
uint8 CLOSED       = 3\n\
uint8 OPEN         = 4\n\
\n\
uint8 state\n\
";
  }

  static const char* value(const ::ff_msgs::ArmGripperState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ff_msgs::ArmGripperState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmGripperState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ff_msgs::ArmGripperState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ff_msgs::ArmGripperState_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FF_MSGS_MESSAGE_ARMGRIPPERSTATE_H
