// Generated by gencpp from file ff_msgs/CameraState.msg
// DO NOT EDIT!


#ifndef FF_MSGS_MESSAGE_CAMERASTATE_H
#define FF_MSGS_MESSAGE_CAMERASTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ff_msgs
{
template <class ContainerAllocator>
struct CameraState_
{
  typedef CameraState_<ContainerAllocator> Type;

  CameraState_()
    : camera_name()
    , streaming(false)
    , stream_width(0)
    , stream_height(0)
    , stream_rate(0.0)
    , recording(false)
    , record_width(0)
    , record_height(0)
    , record_rate(0.0)
    , bandwidth(0.0)  {
    }
  CameraState_(const ContainerAllocator& _alloc)
    : camera_name(_alloc)
    , streaming(false)
    , stream_width(0)
    , stream_height(0)
    , stream_rate(0.0)
    , recording(false)
    , record_width(0)
    , record_height(0)
    , record_rate(0.0)
    , bandwidth(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _camera_name_type;
  _camera_name_type camera_name;

   typedef uint8_t _streaming_type;
  _streaming_type streaming;

   typedef uint16_t _stream_width_type;
  _stream_width_type stream_width;

   typedef uint16_t _stream_height_type;
  _stream_height_type stream_height;

   typedef float _stream_rate_type;
  _stream_rate_type stream_rate;

   typedef uint8_t _recording_type;
  _recording_type recording;

   typedef uint16_t _record_width_type;
  _record_width_type record_width;

   typedef uint16_t _record_height_type;
  _record_height_type record_height;

   typedef float _record_rate_type;
  _record_rate_type record_rate;

   typedef float _bandwidth_type;
  _bandwidth_type bandwidth;





  typedef boost::shared_ptr< ::ff_msgs::CameraState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ff_msgs::CameraState_<ContainerAllocator> const> ConstPtr;

}; // struct CameraState_

typedef ::ff_msgs::CameraState_<std::allocator<void> > CameraState;

typedef boost::shared_ptr< ::ff_msgs::CameraState > CameraStatePtr;
typedef boost::shared_ptr< ::ff_msgs::CameraState const> CameraStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ff_msgs::CameraState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ff_msgs::CameraState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ff_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/std_msgs/cmake/../msg', '/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ff_msgs': ['/home/isuru/Forked_astrobee/astrobee/src/communications/ff_msgs/msg', '/home/isuru/Forked_astrobee/astrobee/debian/devel/.private/ff_msgs/share/ff_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ff_msgs::CameraState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ff_msgs::CameraState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ff_msgs::CameraState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ff_msgs::CameraState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ff_msgs::CameraState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ff_msgs::CameraState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ff_msgs::CameraState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "644cfd14384d17cf28911b625a446f53";
  }

  static const char* value(const ::ff_msgs::CameraState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x644cfd14384d17cfULL;
  static const uint64_t static_value2 = 0x28911b625a446f53ULL;
};

template<class ContainerAllocator>
struct DataType< ::ff_msgs::CameraState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff_msgs/CameraState";
  }

  static const char* value(const ::ff_msgs::CameraState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ff_msgs::CameraState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright (c) 2017, United States Government, as represented by the\n\
# Administrator of the National Aeronautics and Space Administration.\n\
# \n\
# All rights reserved.\n\
# \n\
# The Astrobee platform is licensed under the Apache License, Version 2.0\n\
# (the \"License\"); you may not use this file except in compliance with the\n\
# License. You may obtain a copy of the License at\n\
# \n\
#     http://www.apache.org/licenses/LICENSE-2.0\n\
# \n\
# Unless required by applicable law or agreed to in writing, software\n\
# distributed under the License is distributed on an \"AS IS\" BASIS, WITHOUT\n\
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the\n\
# License for the specific language governing permissions and limitations\n\
# under the License.\n\
#\n\
# CameraState message, *MUST* be kept in sync with camera portion of\n\
# rapid::ext::astrobee::TelemetryState\n\
\n\
# nav_cam, dock_cam, etc.\n\
string camera_name\n\
\n\
# streaming to ground\n\
bool streaming\n\
\n\
# image width\n\
uint16 stream_width\n\
# image height\n\
uint16 stream_height\n\
# Rate in Hz\n\
float32 stream_rate\n\
\n\
# recording to disk\n\
bool recording\n\
\n\
# image width\n\
uint16 record_width\n\
# image height\n\
uint16 record_height\n\
# Rate in Hz\n\
float32 record_rate\n\
\n\
# only for sci cam\n\
float32 bandwidth\n\
";
  }

  static const char* value(const ::ff_msgs::CameraState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ff_msgs::CameraState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.camera_name);
      stream.next(m.streaming);
      stream.next(m.stream_width);
      stream.next(m.stream_height);
      stream.next(m.stream_rate);
      stream.next(m.recording);
      stream.next(m.record_width);
      stream.next(m.record_height);
      stream.next(m.record_rate);
      stream.next(m.bandwidth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ff_msgs::CameraState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ff_msgs::CameraState_<ContainerAllocator>& v)
  {
    s << indent << "camera_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.camera_name);
    s << indent << "streaming: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.streaming);
    s << indent << "stream_width: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.stream_width);
    s << indent << "stream_height: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.stream_height);
    s << indent << "stream_rate: ";
    Printer<float>::stream(s, indent + "  ", v.stream_rate);
    s << indent << "recording: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.recording);
    s << indent << "record_width: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.record_width);
    s << indent << "record_height: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.record_height);
    s << indent << "record_rate: ";
    Printer<float>::stream(s, indent + "  ", v.record_rate);
    s << indent << "bandwidth: ";
    Printer<float>::stream(s, indent + "  ", v.bandwidth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FF_MSGS_MESSAGE_CAMERASTATE_H
