// Generated by gencpp from file ff_msgs/DockState.msg
// DO NOT EDIT!


#ifndef FF_MSGS_MESSAGE_DOCKSTATE_H
#define FF_MSGS_MESSAGE_DOCKSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ff_msgs
{
template <class ContainerAllocator>
struct DockState_
{
  typedef DockState_<ContainerAllocator> Type;

  DockState_()
    : header()
    , state(0)
    , fsm_event()
    , fsm_state()  {
    }
  DockState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(0)
    , fsm_event(_alloc)
    , fsm_state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _fsm_event_type;
  _fsm_event_type fsm_event;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _fsm_state_type;
  _fsm_state_type fsm_state;



  enum {
    RECOVERY_SWITCHING_TO_ML_LOC = 15,
    RECOVERY_MOVING_TO_APPROACH_POSE = 14,
    RECOVERY_WAITING_FOR_SPIN_DOWN = 13,
    RECOVERY_SWITCHING_TO_NO_LOC = 12,
    INITIALIZING = 11,
    UNKNOWN = 10,
    DOCKING_MAX_STATE = 7,
    DOCKING_SWITCHING_TO_ML_LOC = 7,
    DOCKING_MOVING_TO_APPROACH_POSE = 6,
    DOCKING_SWITCHING_TO_AR_LOC = 5,
    DOCKING_MOVING_TO_COMPLETE_POSE = 4,
    DOCKING_CHECKING_ATTACHED = 3,
    DOCKING_WAITING_FOR_SPIN_DOWN = 2,
    DOCKING_SWITCHING_TO_NO_LOC = 1,
    DOCKED = 0,
    UNDOCKING_SWITCHING_TO_ML_LOC = -1,
    UNDOCKING_WAITING_FOR_SPIN_UP = -2,
    UNDOCKING_MOVING_TO_APPROACH_POSE = -3,
    UNDOCKED = -4,
    UNDOCKING_MAX_STATE = -4,
  };


  typedef boost::shared_ptr< ::ff_msgs::DockState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ff_msgs::DockState_<ContainerAllocator> const> ConstPtr;

}; // struct DockState_

typedef ::ff_msgs::DockState_<std::allocator<void> > DockState;

typedef boost::shared_ptr< ::ff_msgs::DockState > DockStatePtr;
typedef boost::shared_ptr< ::ff_msgs::DockState const> DockStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ff_msgs::DockState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ff_msgs::DockState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ff_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/std_msgs/cmake/../msg', '/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ff_msgs': ['/home/isuru/Forked_astrobee/astrobee/src/communications/ff_msgs/msg', '/home/isuru/Forked_astrobee/astrobee/debian/devel/.private/ff_msgs/share/ff_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ff_msgs::DockState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ff_msgs::DockState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ff_msgs::DockState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ff_msgs::DockState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ff_msgs::DockState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ff_msgs::DockState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ff_msgs::DockState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09d842ed9109dbc2bf96976f8fb2eaa5";
  }

  static const char* value(const ::ff_msgs::DockState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09d842ed9109dbc2ULL;
  static const uint64_t static_value2 = 0xbf96976f8fb2eaa5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ff_msgs::DockState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff_msgs/DockState";
  }

  static const char* value(const ::ff_msgs::DockState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ff_msgs::DockState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright (c) 2017, United States Government, as represented by the\n\
# Administrator of the National Aeronautics and Space Administration.\n\
# \n\
# All rights reserved.\n\
# \n\
# The Astrobee platform is licensed under the Apache License, Version 2.0\n\
# (the \"License\"); you may not use this file except in compliance with the\n\
# License. You may obtain a copy of the License at\n\
# \n\
#     http://www.apache.org/licenses/LICENSE-2.0\n\
# \n\
# Unless required by applicable law or agreed to in writing, software\n\
# distributed under the License is distributed on an \"AS IS\" BASIS, WITHOUT\n\
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the\n\
# License for the specific language governing permissions and limitations\n\
# under the License.\n\
#\n\
# Response for Dock/Undock goals\n\
\n\
# Header with timestamp\n\
std_msgs/Header header\n\
\n\
# Feedback\n\
int8 state\n\
int8 RECOVERY_SWITCHING_TO_ML_LOC       = 15\n\
int8 RECOVERY_MOVING_TO_APPROACH_POSE   = 14\n\
int8 RECOVERY_WAITING_FOR_SPIN_DOWN     = 13\n\
int8 RECOVERY_SWITCHING_TO_NO_LOC       = 12\n\
int8 INITIALIZING                       = 11\n\
int8 UNKNOWN                            = 10\n\
int8 DOCKING_MAX_STATE                  = 7\n\
int8 DOCKING_SWITCHING_TO_ML_LOC        = 7\n\
int8 DOCKING_MOVING_TO_APPROACH_POSE    = 6\n\
int8 DOCKING_SWITCHING_TO_AR_LOC        = 5\n\
int8 DOCKING_MOVING_TO_COMPLETE_POSE    = 4\n\
int8 DOCKING_CHECKING_ATTACHED          = 3\n\
int8 DOCKING_WAITING_FOR_SPIN_DOWN      = 2\n\
int8 DOCKING_SWITCHING_TO_NO_LOC        = 1\n\
int8 DOCKED                             = 0\n\
int8 UNDOCKING_SWITCHING_TO_ML_LOC      = -1\n\
int8 UNDOCKING_WAITING_FOR_SPIN_UP      = -2\n\
int8 UNDOCKING_MOVING_TO_APPROACH_POSE  = -3\n\
int8 UNDOCKED                           = -4\n\
int8 UNDOCKING_MAX_STATE                = -4\n\
\n\
# A human readble version of the (event) -> [state] transition\n\
string fsm_event\n\
string fsm_state\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ff_msgs::DockState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ff_msgs::DockState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
      stream.next(m.fsm_event);
      stream.next(m.fsm_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DockState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ff_msgs::DockState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ff_msgs::DockState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
    s << indent << "fsm_event: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.fsm_event);
    s << indent << "fsm_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.fsm_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FF_MSGS_MESSAGE_DOCKSTATE_H
