// Generated by gencpp from file ff_msgs/GetZones.msg
// DO NOT EDIT!


#ifndef FF_MSGS_MESSAGE_GETZONES_H
#define FF_MSGS_MESSAGE_GETZONES_H

#include <ros/service_traits.h>


#include <ff_msgs/GetZonesRequest.h>
#include <ff_msgs/GetZonesResponse.h>


namespace ff_msgs
{

struct GetZones
{

typedef GetZonesRequest Request;
typedef GetZonesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetZones
} // namespace ff_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ff_msgs::GetZones > {
  static const char* value()
  {
    return "bcb94608c442ab09483e9fcbedd6ba7d";
  }

  static const char* value(const ::ff_msgs::GetZones&) { return value(); }
};

template<>
struct DataType< ::ff_msgs::GetZones > {
  static const char* value()
  {
    return "ff_msgs/GetZones";
  }

  static const char* value(const ::ff_msgs::GetZones&) { return value(); }
};


// service_traits::MD5Sum< ::ff_msgs::GetZonesRequest> should match 
// service_traits::MD5Sum< ::ff_msgs::GetZones > 
template<>
struct MD5Sum< ::ff_msgs::GetZonesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ff_msgs::GetZones >::value();
  }
  static const char* value(const ::ff_msgs::GetZonesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ff_msgs::GetZonesRequest> should match 
// service_traits::DataType< ::ff_msgs::GetZones > 
template<>
struct DataType< ::ff_msgs::GetZonesRequest>
{
  static const char* value()
  {
    return DataType< ::ff_msgs::GetZones >::value();
  }
  static const char* value(const ::ff_msgs::GetZonesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ff_msgs::GetZonesResponse> should match 
// service_traits::MD5Sum< ::ff_msgs::GetZones > 
template<>
struct MD5Sum< ::ff_msgs::GetZonesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ff_msgs::GetZones >::value();
  }
  static const char* value(const ::ff_msgs::GetZonesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ff_msgs::GetZonesResponse> should match 
// service_traits::DataType< ::ff_msgs::GetZones > 
template<>
struct DataType< ::ff_msgs::GetZonesResponse>
{
  static const char* value()
  {
    return DataType< ::ff_msgs::GetZones >::value();
  }
  static const char* value(const ::ff_msgs::GetZonesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FF_MSGS_MESSAGE_GETZONES_H
