// Generated by gencpp from file ff_msgs/GetZonesResponse.msg
// DO NOT EDIT!


#ifndef FF_MSGS_MESSAGE_GETZONESRESPONSE_H
#define FF_MSGS_MESSAGE_GETZONESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ff_msgs/Zone.h>

namespace ff_msgs
{
template <class ContainerAllocator>
struct GetZonesResponse_
{
  typedef GetZonesResponse_<ContainerAllocator> Type;

  GetZonesResponse_()
    : timestamp()
    , zones()  {
    }
  GetZonesResponse_(const ContainerAllocator& _alloc)
    : timestamp()
    , zones(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef std::vector< ::ff_msgs::Zone_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ff_msgs::Zone_<ContainerAllocator> >::other >  _zones_type;
  _zones_type zones;





  typedef boost::shared_ptr< ::ff_msgs::GetZonesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ff_msgs::GetZonesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetZonesResponse_

typedef ::ff_msgs::GetZonesResponse_<std::allocator<void> > GetZonesResponse;

typedef boost::shared_ptr< ::ff_msgs::GetZonesResponse > GetZonesResponsePtr;
typedef boost::shared_ptr< ::ff_msgs::GetZonesResponse const> GetZonesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ff_msgs::GetZonesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ff_msgs::GetZonesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ff_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/std_msgs/cmake/../msg', '/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ff_msgs': ['/home/isuru/Forked_astrobee/astrobee/src/communications/ff_msgs/msg', '/home/isuru/Forked_astrobee/astrobee/debian/devel/.private/ff_msgs/share/ff_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ff_msgs::GetZonesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ff_msgs::GetZonesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ff_msgs::GetZonesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ff_msgs::GetZonesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ff_msgs::GetZonesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ff_msgs::GetZonesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ff_msgs::GetZonesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bcb94608c442ab09483e9fcbedd6ba7d";
  }

  static const char* value(const ::ff_msgs::GetZonesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbcb94608c442ab09ULL;
  static const uint64_t static_value2 = 0x483e9fcbedd6ba7dULL;
};

template<class ContainerAllocator>
struct DataType< ::ff_msgs::GetZonesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff_msgs/GetZonesResponse";
  }

  static const char* value(const ::ff_msgs::GetZonesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ff_msgs::GetZonesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time timestamp\n\
ff_msgs/Zone[] zones\n\
\n\
================================================================================\n\
MSG: ff_msgs/Zone\n\
# Copyright (c) 2017, United States Government, as represented by the\n\
# Administrator of the National Aeronautics and Space Administration.\n\
# \n\
# All rights reserved.\n\
# \n\
# The Astrobee platform is licensed under the Apache License, Version 2.0\n\
# (the \"License\"); you may not use this file except in compliance with the\n\
# License. You may obtain a copy of the License at\n\
# \n\
#     http://www.apache.org/licenses/LICENSE-2.0\n\
# \n\
# Unless required by applicable law or agreed to in writing, software\n\
# distributed under the License is distributed on an \"AS IS\" BASIS, WITHOUT\n\
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the\n\
# License for the specific language governing permissions and limitations\n\
# under the License.\n\
#\n\
# This message defines a zone, such as a Keepin or Keeoput.\n\
\n\
string name                   # Name of zone\n\
\n\
# A name can refer to multiple zones. This is the index of the zone with respect\n\
# to the zone name\n\
int32 index\n\
\n\
# Zone type\n\
uint8 KEEPOUT = 0       # An area the freeflyer should stay out of\n\
uint8 KEEPIN  = 1       # An area the freeflyer can fly freely in \n\
uint8 CLUTTER = 2       # An area that the freeflyer should avoid due to clutter\n\
\n\
uint8 type              # Whether the zone is a keepin, keepout, or clutter\n\
\n\
geometry_msgs/Vector3 min   # One corner of the zone\n\
geometry_msgs/Vector3 max   # The opposite corner of the zone\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::ff_msgs::GetZonesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ff_msgs::GetZonesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.zones);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetZonesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ff_msgs::GetZonesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ff_msgs::GetZonesResponse_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "zones[]" << std::endl;
    for (size_t i = 0; i < v.zones.size(); ++i)
    {
      s << indent << "  zones[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ff_msgs::Zone_<ContainerAllocator> >::stream(s, indent + "    ", v.zones[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FF_MSGS_MESSAGE_GETZONESRESPONSE_H
