// Generated by gencpp from file ff_msgs/MotionState.msg
// DO NOT EDIT!


#ifndef FF_MSGS_MESSAGE_MOTIONSTATE_H
#define FF_MSGS_MESSAGE_MOTIONSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ff_msgs
{
template <class ContainerAllocator>
struct MotionState_
{
  typedef MotionState_<ContainerAllocator> Type;

  MotionState_()
    : header()
    , state(0)
    , fsm_event()
    , fsm_state()  {
    }
  MotionState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(0)
    , fsm_event(_alloc)
    , fsm_state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _fsm_event_type;
  _fsm_event_type fsm_event;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _fsm_state_type;
  _fsm_state_type fsm_state;



  enum {
    INITIALIZING = 0,
    IDLE = 1,
    STOPPED = 2,
    IDLING = 3,
    STOPPING = 4,
    PREPPING = 5,
    BOOTSTRAPPING = 6,
    PLANNING = 7,
    PREPARING = 8,
    CONTROLLING = 9,
    REPLANNING = 10,
    HALTING = 11,
    REPLAN_WAIT = 12,
  };


  typedef boost::shared_ptr< ::ff_msgs::MotionState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ff_msgs::MotionState_<ContainerAllocator> const> ConstPtr;

}; // struct MotionState_

typedef ::ff_msgs::MotionState_<std::allocator<void> > MotionState;

typedef boost::shared_ptr< ::ff_msgs::MotionState > MotionStatePtr;
typedef boost::shared_ptr< ::ff_msgs::MotionState const> MotionStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ff_msgs::MotionState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ff_msgs::MotionState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ff_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/std_msgs/cmake/../msg', '/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ff_msgs': ['/home/isuru/Forked_astrobee/astrobee/src/communications/ff_msgs/msg', '/home/isuru/Forked_astrobee/astrobee/debian/devel/.private/ff_msgs/share/ff_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ff_msgs::MotionState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ff_msgs::MotionState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ff_msgs::MotionState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ff_msgs::MotionState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ff_msgs::MotionState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ff_msgs::MotionState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ff_msgs::MotionState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca36119625f2a1b66f63a30344414dac";
  }

  static const char* value(const ::ff_msgs::MotionState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca36119625f2a1b6ULL;
  static const uint64_t static_value2 = 0x6f63a30344414dacULL;
};

template<class ContainerAllocator>
struct DataType< ::ff_msgs::MotionState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff_msgs/MotionState";
  }

  static const char* value(const ::ff_msgs::MotionState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ff_msgs::MotionState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright (c) 2017, United States Government, as represented by the\n\
# Administrator of the National Aeronautics and Space Administration.\n\
#\n\
# All rights reserved.\n\
#\n\
# The Astrobee platform is licensed under the Apache License, Version 2.0\n\
# (the \"License\"); you may not use this file except in compliance with the\n\
# License. You may obtain a copy of the License at\n\
#\n\
#     http://www.apache.org/licenses/LICENSE-2.0\n\
#\n\
# Unless required by applicable law or agreed to in writing, software\n\
# distributed under the License is distributed on an \"AS IS\" BASIS, WITHOUT\n\
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the\n\
# License for the specific language governing permissions and limitations\n\
# under the License.\n\
#\n\
# Locked topic that registers updates to the internal dock state\n\
\n\
# Header with timestamp\n\
std_msgs/Header header\n\
\n\
# The state of the mobility subsystem\n\
int8 state\n\
int8 INITIALIZING        = 0\n\
int8 IDLE                = 1\n\
int8 STOPPED             = 2\n\
int8 IDLING              = 3\n\
int8 STOPPING            = 4\n\
int8 PREPPING            = 5\n\
int8 BOOTSTRAPPING       = 6\n\
int8 PLANNING            = 7\n\
int8 PREPARING           = 8\n\
int8 CONTROLLING         = 9\n\
int8 REPLANNING          = 10\n\
int8 HALTING             = 11\n\
int8 REPLAN_WAIT         = 12\n\
\n\
# A human readble version of the (event) -> [state] transition\n\
string fsm_event\n\
string fsm_state\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ff_msgs::MotionState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ff_msgs::MotionState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
      stream.next(m.fsm_event);
      stream.next(m.fsm_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotionState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ff_msgs::MotionState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ff_msgs::MotionState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
    s << indent << "fsm_event: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.fsm_event);
    s << indent << "fsm_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.fsm_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FF_MSGS_MESSAGE_MOTIONSTATE_H
