// Generated by gencpp from file ff_msgs/SetBool.msg
// DO NOT EDIT!


#ifndef FF_MSGS_MESSAGE_SETBOOL_H
#define FF_MSGS_MESSAGE_SETBOOL_H

#include <ros/service_traits.h>


#include <ff_msgs/SetBoolRequest.h>
#include <ff_msgs/SetBoolResponse.h>


namespace ff_msgs
{

struct SetBool
{

typedef SetBoolRequest Request;
typedef SetBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBool
} // namespace ff_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ff_msgs::SetBool > {
  static const char* value()
  {
    return "6a0b406242562fc416b2c9c8a3efb051";
  }

  static const char* value(const ::ff_msgs::SetBool&) { return value(); }
};

template<>
struct DataType< ::ff_msgs::SetBool > {
  static const char* value()
  {
    return "ff_msgs/SetBool";
  }

  static const char* value(const ::ff_msgs::SetBool&) { return value(); }
};


// service_traits::MD5Sum< ::ff_msgs::SetBoolRequest> should match 
// service_traits::MD5Sum< ::ff_msgs::SetBool > 
template<>
struct MD5Sum< ::ff_msgs::SetBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ff_msgs::SetBool >::value();
  }
  static const char* value(const ::ff_msgs::SetBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ff_msgs::SetBoolRequest> should match 
// service_traits::DataType< ::ff_msgs::SetBool > 
template<>
struct DataType< ::ff_msgs::SetBoolRequest>
{
  static const char* value()
  {
    return DataType< ::ff_msgs::SetBool >::value();
  }
  static const char* value(const ::ff_msgs::SetBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ff_msgs::SetBoolResponse> should match 
// service_traits::MD5Sum< ::ff_msgs::SetBool > 
template<>
struct MD5Sum< ::ff_msgs::SetBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ff_msgs::SetBool >::value();
  }
  static const char* value(const ::ff_msgs::SetBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ff_msgs::SetBoolResponse> should match 
// service_traits::DataType< ::ff_msgs::SetBool > 
template<>
struct DataType< ::ff_msgs::SetBoolResponse>
{
  static const char* value()
  {
    return DataType< ::ff_msgs::SetBool >::value();
  }
  static const char* value(const ::ff_msgs::SetBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FF_MSGS_MESSAGE_SETBOOL_H
