// Generated by gencpp from file ff_msgs/SetDataToDisk.msg
// DO NOT EDIT!


#ifndef FF_MSGS_MESSAGE_SETDATATODISK_H
#define FF_MSGS_MESSAGE_SETDATATODISK_H

#include <ros/service_traits.h>


#include <ff_msgs/SetDataToDiskRequest.h>
#include <ff_msgs/SetDataToDiskResponse.h>


namespace ff_msgs
{

struct SetDataToDisk
{

typedef SetDataToDiskRequest Request;
typedef SetDataToDiskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDataToDisk
} // namespace ff_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ff_msgs::SetDataToDisk > {
  static const char* value()
  {
    return "b4cc86540abfc221f4a113bbc42f4b5c";
  }

  static const char* value(const ::ff_msgs::SetDataToDisk&) { return value(); }
};

template<>
struct DataType< ::ff_msgs::SetDataToDisk > {
  static const char* value()
  {
    return "ff_msgs/SetDataToDisk";
  }

  static const char* value(const ::ff_msgs::SetDataToDisk&) { return value(); }
};


// service_traits::MD5Sum< ::ff_msgs::SetDataToDiskRequest> should match 
// service_traits::MD5Sum< ::ff_msgs::SetDataToDisk > 
template<>
struct MD5Sum< ::ff_msgs::SetDataToDiskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ff_msgs::SetDataToDisk >::value();
  }
  static const char* value(const ::ff_msgs::SetDataToDiskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ff_msgs::SetDataToDiskRequest> should match 
// service_traits::DataType< ::ff_msgs::SetDataToDisk > 
template<>
struct DataType< ::ff_msgs::SetDataToDiskRequest>
{
  static const char* value()
  {
    return DataType< ::ff_msgs::SetDataToDisk >::value();
  }
  static const char* value(const ::ff_msgs::SetDataToDiskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ff_msgs::SetDataToDiskResponse> should match 
// service_traits::MD5Sum< ::ff_msgs::SetDataToDisk > 
template<>
struct MD5Sum< ::ff_msgs::SetDataToDiskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ff_msgs::SetDataToDisk >::value();
  }
  static const char* value(const ::ff_msgs::SetDataToDiskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ff_msgs::SetDataToDiskResponse> should match 
// service_traits::DataType< ::ff_msgs::SetDataToDisk > 
template<>
struct DataType< ::ff_msgs::SetDataToDiskResponse>
{
  static const char* value()
  {
    return DataType< ::ff_msgs::SetDataToDisk >::value();
  }
  static const char* value(const ::ff_msgs::SetDataToDiskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FF_MSGS_MESSAGE_SETDATATODISK_H
