// Generated by gencpp from file ff_msgs/SetStreamingLights.msg
// DO NOT EDIT!


#ifndef FF_MSGS_MESSAGE_SETSTREAMINGLIGHTS_H
#define FF_MSGS_MESSAGE_SETSTREAMINGLIGHTS_H

#include <ros/service_traits.h>


#include <ff_msgs/SetStreamingLightsRequest.h>
#include <ff_msgs/SetStreamingLightsResponse.h>


namespace ff_msgs
{

struct SetStreamingLights
{

typedef SetStreamingLightsRequest Request;
typedef SetStreamingLightsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetStreamingLights
} // namespace ff_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ff_msgs::SetStreamingLights > {
  static const char* value()
  {
    return "4581db74aae4efc6534413a8b210908c";
  }

  static const char* value(const ::ff_msgs::SetStreamingLights&) { return value(); }
};

template<>
struct DataType< ::ff_msgs::SetStreamingLights > {
  static const char* value()
  {
    return "ff_msgs/SetStreamingLights";
  }

  static const char* value(const ::ff_msgs::SetStreamingLights&) { return value(); }
};


// service_traits::MD5Sum< ::ff_msgs::SetStreamingLightsRequest> should match 
// service_traits::MD5Sum< ::ff_msgs::SetStreamingLights > 
template<>
struct MD5Sum< ::ff_msgs::SetStreamingLightsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ff_msgs::SetStreamingLights >::value();
  }
  static const char* value(const ::ff_msgs::SetStreamingLightsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ff_msgs::SetStreamingLightsRequest> should match 
// service_traits::DataType< ::ff_msgs::SetStreamingLights > 
template<>
struct DataType< ::ff_msgs::SetStreamingLightsRequest>
{
  static const char* value()
  {
    return DataType< ::ff_msgs::SetStreamingLights >::value();
  }
  static const char* value(const ::ff_msgs::SetStreamingLightsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ff_msgs::SetStreamingLightsResponse> should match 
// service_traits::MD5Sum< ::ff_msgs::SetStreamingLights > 
template<>
struct MD5Sum< ::ff_msgs::SetStreamingLightsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ff_msgs::SetStreamingLights >::value();
  }
  static const char* value(const ::ff_msgs::SetStreamingLightsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ff_msgs::SetStreamingLightsResponse> should match 
// service_traits::DataType< ::ff_msgs::SetStreamingLights > 
template<>
struct DataType< ::ff_msgs::SetStreamingLightsResponse>
{
  static const char* value()
  {
    return DataType< ::ff_msgs::SetStreamingLights >::value();
  }
  static const char* value(const ::ff_msgs::SetStreamingLightsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FF_MSGS_MESSAGE_SETSTREAMINGLIGHTS_H
