// Generated by gencpp from file ff_msgs/TimeSyncStamped.msg
// DO NOT EDIT!


#ifndef FF_MSGS_MESSAGE_TIMESYNCSTAMPED_H
#define FF_MSGS_MESSAGE_TIMESYNCSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ff_msgs
{
template <class ContainerAllocator>
struct TimeSyncStamped_
{
  typedef TimeSyncStamped_<ContainerAllocator> Type;

  TimeSyncStamped_()
    : header()
    , remote_processor()
    , mlp_time()
    , remote_time()  {
    }
  TimeSyncStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , remote_processor(_alloc)
    , mlp_time()
    , remote_time()  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _remote_processor_type;
  _remote_processor_type remote_processor;

   typedef ros::Time _mlp_time_type;
  _mlp_time_type mlp_time;

   typedef ros::Time _remote_time_type;
  _remote_time_type remote_time;





  typedef boost::shared_ptr< ::ff_msgs::TimeSyncStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ff_msgs::TimeSyncStamped_<ContainerAllocator> const> ConstPtr;

}; // struct TimeSyncStamped_

typedef ::ff_msgs::TimeSyncStamped_<std::allocator<void> > TimeSyncStamped;

typedef boost::shared_ptr< ::ff_msgs::TimeSyncStamped > TimeSyncStampedPtr;
typedef boost::shared_ptr< ::ff_msgs::TimeSyncStamped const> TimeSyncStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ff_msgs::TimeSyncStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ff_msgs::TimeSyncStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ff_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/std_msgs/cmake/../msg', '/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ff_msgs': ['/home/isuru/Forked_astrobee/astrobee/src/communications/ff_msgs/msg', '/home/isuru/Forked_astrobee/astrobee/debian/devel/.private/ff_msgs/share/ff_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ff_msgs::TimeSyncStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ff_msgs::TimeSyncStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ff_msgs::TimeSyncStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ff_msgs::TimeSyncStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ff_msgs::TimeSyncStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ff_msgs::TimeSyncStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ff_msgs::TimeSyncStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37bae83a741b528e46eb78c2ad2d0190";
  }

  static const char* value(const ::ff_msgs::TimeSyncStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37bae83a741b528eULL;
  static const uint64_t static_value2 = 0x46eb78c2ad2d0190ULL;
};

template<class ContainerAllocator>
struct DataType< ::ff_msgs::TimeSyncStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff_msgs/TimeSyncStamped";
  }

  static const char* value(const ::ff_msgs::TimeSyncStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ff_msgs::TimeSyncStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright (c) 2017, United States Government, as represented by the\n\
# Administrator of the National Aeronautics and Space Administration.\n\
# \n\
# All rights reserved.\n\
# \n\
# The Astrobee platform is licensed under the Apache License, Version 2.0\n\
# (the \"License\"); you may not use this file except in compliance with the\n\
# License. You may obtain a copy of the License at\n\
# \n\
#     http://www.apache.org/licenses/LICENSE-2.0\n\
# \n\
# Unless required by applicable law or agreed to in writing, software\n\
# distributed under the License is distributed on an \"AS IS\" BASIS, WITHOUT\n\
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the\n\
# License for the specific language governing permissions and limitations\n\
# under the License.\n\
#\n\
# Message to send time difference between the mlp and llp\n\
\n\
# Header with timestamp\n\
std_msgs/Header header\n\
\n\
# Processor that the heartbeat came from\n\
string remote_processor\n\
\n\
# Current time on the mlp\n\
time mlp_time\n\
\n\
# Time in the incoming heartbeat\n\
time remote_time\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ff_msgs::TimeSyncStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ff_msgs::TimeSyncStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.remote_processor);
      stream.next(m.mlp_time);
      stream.next(m.remote_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimeSyncStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ff_msgs::TimeSyncStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ff_msgs::TimeSyncStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "remote_processor: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.remote_processor);
    s << indent << "mlp_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.mlp_time);
    s << indent << "remote_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.remote_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FF_MSGS_MESSAGE_TIMESYNCSTAMPED_H
