// Generated by gencpp from file ff_msgs/Trigger.msg
// DO NOT EDIT!


#ifndef FF_MSGS_MESSAGE_TRIGGER_H
#define FF_MSGS_MESSAGE_TRIGGER_H

#include <ros/service_traits.h>


#include <ff_msgs/TriggerRequest.h>
#include <ff_msgs/TriggerResponse.h>


namespace ff_msgs
{

struct Trigger
{

typedef TriggerRequest Request;
typedef TriggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Trigger
} // namespace ff_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ff_msgs::Trigger > {
  static const char* value()
  {
    return "15235914233b414e535b7900827f7f14";
  }

  static const char* value(const ::ff_msgs::Trigger&) { return value(); }
};

template<>
struct DataType< ::ff_msgs::Trigger > {
  static const char* value()
  {
    return "ff_msgs/Trigger";
  }

  static const char* value(const ::ff_msgs::Trigger&) { return value(); }
};


// service_traits::MD5Sum< ::ff_msgs::TriggerRequest> should match 
// service_traits::MD5Sum< ::ff_msgs::Trigger > 
template<>
struct MD5Sum< ::ff_msgs::TriggerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ff_msgs::Trigger >::value();
  }
  static const char* value(const ::ff_msgs::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ff_msgs::TriggerRequest> should match 
// service_traits::DataType< ::ff_msgs::Trigger > 
template<>
struct DataType< ::ff_msgs::TriggerRequest>
{
  static const char* value()
  {
    return DataType< ::ff_msgs::Trigger >::value();
  }
  static const char* value(const ::ff_msgs::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ff_msgs::TriggerResponse> should match 
// service_traits::MD5Sum< ::ff_msgs::Trigger > 
template<>
struct MD5Sum< ::ff_msgs::TriggerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ff_msgs::Trigger >::value();
  }
  static const char* value(const ::ff_msgs::TriggerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ff_msgs::TriggerResponse> should match 
// service_traits::DataType< ::ff_msgs::Trigger > 
template<>
struct DataType< ::ff_msgs::TriggerResponse>
{
  static const char* value()
  {
    return DataType< ::ff_msgs::Trigger >::value();
  }
  static const char* value(const ::ff_msgs::TriggerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FF_MSGS_MESSAGE_TRIGGER_H
