// Generated by gencpp from file ff_msgs/UnloadLoadNodelet.msg
// DO NOT EDIT!


#ifndef FF_MSGS_MESSAGE_UNLOADLOADNODELET_H
#define FF_MSGS_MESSAGE_UNLOADLOADNODELET_H

#include <ros/service_traits.h>


#include <ff_msgs/UnloadLoadNodeletRequest.h>
#include <ff_msgs/UnloadLoadNodeletResponse.h>


namespace ff_msgs
{

struct UnloadLoadNodelet
{

typedef UnloadLoadNodeletRequest Request;
typedef UnloadLoadNodeletResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UnloadLoadNodelet
} // namespace ff_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ff_msgs::UnloadLoadNodelet > {
  static const char* value()
  {
    return "7f19eb1a2a34b5a95695a9d88b20e227";
  }

  static const char* value(const ::ff_msgs::UnloadLoadNodelet&) { return value(); }
};

template<>
struct DataType< ::ff_msgs::UnloadLoadNodelet > {
  static const char* value()
  {
    return "ff_msgs/UnloadLoadNodelet";
  }

  static const char* value(const ::ff_msgs::UnloadLoadNodelet&) { return value(); }
};


// service_traits::MD5Sum< ::ff_msgs::UnloadLoadNodeletRequest> should match 
// service_traits::MD5Sum< ::ff_msgs::UnloadLoadNodelet > 
template<>
struct MD5Sum< ::ff_msgs::UnloadLoadNodeletRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ff_msgs::UnloadLoadNodelet >::value();
  }
  static const char* value(const ::ff_msgs::UnloadLoadNodeletRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ff_msgs::UnloadLoadNodeletRequest> should match 
// service_traits::DataType< ::ff_msgs::UnloadLoadNodelet > 
template<>
struct DataType< ::ff_msgs::UnloadLoadNodeletRequest>
{
  static const char* value()
  {
    return DataType< ::ff_msgs::UnloadLoadNodelet >::value();
  }
  static const char* value(const ::ff_msgs::UnloadLoadNodeletRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ff_msgs::UnloadLoadNodeletResponse> should match 
// service_traits::MD5Sum< ::ff_msgs::UnloadLoadNodelet > 
template<>
struct MD5Sum< ::ff_msgs::UnloadLoadNodeletResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ff_msgs::UnloadLoadNodelet >::value();
  }
  static const char* value(const ::ff_msgs::UnloadLoadNodeletResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ff_msgs::UnloadLoadNodeletResponse> should match 
// service_traits::DataType< ::ff_msgs::UnloadLoadNodelet > 
template<>
struct DataType< ::ff_msgs::UnloadLoadNodeletResponse>
{
  static const char* value()
  {
    return DataType< ::ff_msgs::UnloadLoadNodelet >::value();
  }
  static const char* value(const ::ff_msgs::UnloadLoadNodeletResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FF_MSGS_MESSAGE_UNLOADLOADNODELET_H
