// Generated by gencpp from file ff_msgs/Zone.msg
// DO NOT EDIT!


#ifndef FF_MSGS_MESSAGE_ZONE_H
#define FF_MSGS_MESSAGE_ZONE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace ff_msgs
{
template <class ContainerAllocator>
struct Zone_
{
  typedef Zone_<ContainerAllocator> Type;

  Zone_()
    : name()
    , index(0)
    , type(0)
    , min()
    , max()  {
    }
  Zone_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , index(0)
    , type(0)
    , min(_alloc)
    , max(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int32_t _index_type;
  _index_type index;

   typedef uint8_t _type_type;
  _type_type type;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _min_type;
  _min_type min;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _max_type;
  _max_type max;



  enum {
    KEEPOUT = 0u,
    KEEPIN = 1u,
    CLUTTER = 2u,
  };


  typedef boost::shared_ptr< ::ff_msgs::Zone_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ff_msgs::Zone_<ContainerAllocator> const> ConstPtr;

}; // struct Zone_

typedef ::ff_msgs::Zone_<std::allocator<void> > Zone;

typedef boost::shared_ptr< ::ff_msgs::Zone > ZonePtr;
typedef boost::shared_ptr< ::ff_msgs::Zone const> ZoneConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ff_msgs::Zone_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ff_msgs::Zone_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ff_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/std_msgs/cmake/../msg', '/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/home/isuru/arm_cross/rootfs/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ff_msgs': ['/home/isuru/Forked_astrobee/astrobee/src/communications/ff_msgs/msg', '/home/isuru/Forked_astrobee/astrobee/debian/devel/.private/ff_msgs/share/ff_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ff_msgs::Zone_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ff_msgs::Zone_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ff_msgs::Zone_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ff_msgs::Zone_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ff_msgs::Zone_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ff_msgs::Zone_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ff_msgs::Zone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb4a7bedb72c164486d2ac45ba0a7b8e";
  }

  static const char* value(const ::ff_msgs::Zone_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb4a7bedb72c1644ULL;
  static const uint64_t static_value2 = 0x86d2ac45ba0a7b8eULL;
};

template<class ContainerAllocator>
struct DataType< ::ff_msgs::Zone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff_msgs/Zone";
  }

  static const char* value(const ::ff_msgs::Zone_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ff_msgs::Zone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright (c) 2017, United States Government, as represented by the\n\
# Administrator of the National Aeronautics and Space Administration.\n\
# \n\
# All rights reserved.\n\
# \n\
# The Astrobee platform is licensed under the Apache License, Version 2.0\n\
# (the \"License\"); you may not use this file except in compliance with the\n\
# License. You may obtain a copy of the License at\n\
# \n\
#     http://www.apache.org/licenses/LICENSE-2.0\n\
# \n\
# Unless required by applicable law or agreed to in writing, software\n\
# distributed under the License is distributed on an \"AS IS\" BASIS, WITHOUT\n\
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the\n\
# License for the specific language governing permissions and limitations\n\
# under the License.\n\
#\n\
# This message defines a zone, such as a Keepin or Keeoput.\n\
\n\
string name                   # Name of zone\n\
\n\
# A name can refer to multiple zones. This is the index of the zone with respect\n\
# to the zone name\n\
int32 index\n\
\n\
# Zone type\n\
uint8 KEEPOUT = 0       # An area the freeflyer should stay out of\n\
uint8 KEEPIN  = 1       # An area the freeflyer can fly freely in \n\
uint8 CLUTTER = 2       # An area that the freeflyer should avoid due to clutter\n\
\n\
uint8 type              # Whether the zone is a keepin, keepout, or clutter\n\
\n\
geometry_msgs/Vector3 min   # One corner of the zone\n\
geometry_msgs/Vector3 max   # The opposite corner of the zone\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::ff_msgs::Zone_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ff_msgs::Zone_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.index);
      stream.next(m.type);
      stream.next(m.min);
      stream.next(m.max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Zone_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ff_msgs::Zone_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ff_msgs::Zone_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "min: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.min);
    s << indent << "max: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FF_MSGS_MESSAGE_ZONE_H
